# Comprehensive URL test cases based on the django-guest-user2 URL structure

URLS_TO_TEST = [
    {
        "path": "/",
        "name": "homepage",
        "title": "Django Guest User Demo Homepage",
        "description": "Main homepage demonstrating django-guest-user2 functionality with navigation",
        "user_type": "anonymous",
        "category": "Navigation",
    },
    {
        "path": "/",
        "name": "homepage_guest",
        "title": "Homepage (Guest User)",
        "description": "Homepage accessed by a guest user showing dynamic user status",
        "user_type": "guest",
        "category": "Navigation",
    },
    {
        "path": "/",
        "name": "homepage_admin",
        "title": "Homepage (Admin User)",
        "description": "Homepage accessed by an admin user showing different user status",
        "user_type": "admin",
        "category": "Navigation",
    },
    {
        "path": "/accounts/profile/",
        "name": "profile_anonymous",
        "title": "User Profile (Anonymous)",
        "description": "User profile page accessed by anonymous user - automatically creates guest account",
        "user_type": "anonymous",
        "category": "User Account",
    },
    {
        "path": "/accounts/profile/",
        "name": "profile_guest",
        "title": "User Profile (Guest User)",
        "description": "User profile page showing guest user information and conversion options",
        "user_type": "guest",
        "category": "User Account",
    },
    {
        "path": "/accounts/profile/",
        "name": "profile_admin",
        "title": "User Profile (Admin User)",
        "description": "User profile page showing admin user information and privileges",
        "user_type": "admin",
        "category": "User Account",
    },
    {
        "path": "/admin/",
        "name": "admin_login",
        "title": "Django Admin Login",
        "description": "Django admin login page - Anonymous user should see login form",
        "user_type": "anonymous",
        "category": "Admin Interface",
    },
    {
        "path": "/admin/",
        "name": "admin_dashboard",
        "title": "Django Admin Dashboard",
        "description": "Django admin dashboard - Logged-in admin should see admin interface",
        "user_type": "admin",
        "requires_login": True,
        "category": "Admin Interface",
    },
    {
        "path": "/allow_guest_user/",
        "name": "allow_guest_user_anonymous",
        "title": "Allow Guest User (Anonymous)",
        "description": "Allow guest user view - Anonymous user gets auto-created guest session",
        "user_type": "anonymous",
        "category": "Decorator Views",
    },
    {
        "path": "/allow_guest_user/",
        "name": "allow_guest_user_guest",
        "title": "Allow Guest User (Guest)",
        "description": "Allow guest user view - Guest user accesses normally",
        "user_type": "guest",
        "category": "Decorator Views",
    },
    {
        "path": "/allow_guest_user/",
        "name": "allow_guest_user_regular",
        "title": "Allow Guest User (Regular)",
        "description": "Allow guest user view - Regular user accesses normally",
        "user_type": "admin",
        "category": "Decorator Views",
    },
    {
        "path": "/guest_user_required/",
        "name": "guest_user_required_anonymous",
        "title": "Guest User Required (Anonymous)",
        "description": "Guest user required view - Anonymous user gets converted to guest automatically",
        "user_type": "anonymous",
        "category": "Decorator Views",
    },
    {
        "path": "/guest_user_required/",
        "name": "guest_user_required_guest",
        "title": "Guest User Required (Guest)",
        "description": "Guest user required view - Guest user accesses normally",
        "user_type": "guest",
        "category": "Decorator Views",
    },
    {
        "path": "/regular_user_required/",
        "name": "regular_user_required_anonymous",
        "title": "Regular User Required (Anonymous)",
        "description": "Regular user required view - Anonymous user should be redirected to login",
        "user_type": "anonymous",
        "category": "Decorator Views",
    },
    {
        "path": "/regular_user_required/",
        "name": "regular_user_required_admin",
        "title": "Regular User Required (Admin)",
        "description": "Regular user required view - Admin user accesses normally",
        "user_type": "admin",
        "category": "Decorator Views",
    },
    {
        "path": "/mixin/allow_guest_user/",
        "name": "mixin_allow_guest_user",
        "title": "Allow Guest User Mixin",
        "description": "Mixin-based allow guest user view - Class-based view equivalent",
        "user_type": "guest",
        "category": "Mixin Views",
    },
    {
        "path": "/mixin/guest_user_required/",
        "name": "mixin_guest_user_required",
        "title": "Guest User Required Mixin",
        "description": "Mixin-based guest user required view - Class-based view equivalent",
        "user_type": "guest",
        "category": "Mixin Views",
    },
    {
        "path": "/mixin/regular_user_required/",
        "name": "mixin_regular_user_required",
        "title": "Regular User Required Mixin",
        "description": "Mixin-based regular user required view - Class-based view equivalent",
        "user_type": "admin",
        "category": "Mixin Views",
    },
    {
        "path": "/convert/",
        "name": "convert_form_anonymous",
        "title": "Convert Form (Anonymous)",
        "description": "Guest conversion form - Anonymous user should be redirected to login first",
        "user_type": "anonymous",
        "category": "Conversion Workflow",
    },
    {
        "path": "/convert/",
        "name": "convert_form_guest",
        "title": "Convert Form (Guest User)",
        "description": "Guest conversion form - Guest user sees conversion form to become regular user",
        "user_type": "guest",
        "interactive": True,
        "category": "Conversion Workflow",
    },
    {
        "path": "/convert/success/",
        "name": "convert_success",
        "title": "Conversion Success Page",
        "description": "Guest conversion success page - Shows after successful conversion",
        "user_type": "guest",
        "category": "Conversion Workflow",
    },
]
